### ISSUE TITLE
Overflow at high steprates

### ISSUE THREAD

**Issue by Wurstnase** [Wurstnase/Marlin#3]
Hi @alexborro,

in issue 1310 you talked about some problems in corexy. Is that similar to my issue?

I think there is some overflow at high steprates.

I've made some tests:
Setup: CoreXY X:320 steps/mm Y:320 steps/mm
With a speed of 150mm/s everything works realy good.
With 166.6 mm/s the motors stops when decellerate. Any ideas?

Also i try to figure out how to increase the max frequency to 85kHz. There are some numbers which cannot reach this. Any help is welcome.

**Comment by Wurstnase** [comment]
I already added in stepper.ccp delayMicroseconds(1) (https://github.com/MarlinFirmware/Marlin/commit/15a00a5a7c5ff5b128ba999428e3b73a980913c8#diff-b1e3f1b10558445963aa5bbf4d20249c)
and i've made the changes with coreXY X_Head and Y_Head.

**Comment by alexborro** [comment]
I have tested the dev branch 2 weeks ago and had no issue, at least visible.
I could move the carriage at 450mm/s in both axis with no problem, with high and low acceleration.

The fix I did was about speed calculation. It was wrong.. 

Are you able to shot a video showing your issue? to be honest I could not understand.

Cheers.

Alex.

**Comment by Wurstnase** [comment]
I thought there is an issue with coreXY which could be the same or similar in bobc-marlin for 32bit.

I implement some changes from marlin-8bit to 32bit (Due/RADDS).
But I have big trouble at higher step-rates. With and withou changes.

At the moment I use 20 teeth pulleys gt2 (2mm) with 1/64 microstepping on a standard nema 17. So I have 320steps/mm. At 166mm/s (10000mm/min) the system crashes after a short while (3 to 5 moves with 100mm).

Maybe I switch back to Ramps/Mega.

**Comment by alexborro** [comment]
@Wurstnase , 1/64 microstepping is insane!!! You will NOT get any "high" speed at such microstepping. The maximum step rate Marlin can keep up is 40 K steps/s, which is not recommended for long term operation due CPU overflow. I usually set 40K steps/s for non-extrusion movements and no more than 20K steps/s for extrusion movement (the last one is more CPU consuming).

In your example, you have 320 steps/mm. That means:
40K steps/s = 125mm/s
20K steps/s = 62,5 mm/s

So don't blame the system.

An advice: Use 1/16 microstepping and you will have 4x more speed with no drawback.

Cheers.

Alex.

**Comment by Wurstnase** [comment]
Sure, that is a high step-rate. 

The Arduino Due has a 85MHz Sam3x. With Repetier you can use 96k steps/s without double/quadstepping. So why not with Marlin?!?

**Comment by alexborro** [comment]
The Stepper routines and ISR are set for maximum 40K steps/s, no matter the CPU speed. 
In order to take advantage of more CPU speed, you need to adjust those routines.. no one have done it so far.. you can be the first  ;-)

Cheers.

Alex.

**Comment by Wurstnase** [comment]
Thanks for making it clear. I think that could be too much for my small skills in programming.

Greatings
Nico
